<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f0c12bdf-f339-4930-ae28-58e548a69fbf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Hello " + 'Input Message' + " from ADS!";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
